name: artifact

on: [push]

env:
  ARTIFACT_NAME: myArtifact
  
jobs:
  main:
    run-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Artifact upload
        uses: actions/upload@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
